cargo-features = ["default-run"]


[package]
name = "rga"
description = "ripgrep, except for pdf, ebooks, Office documents, etc"
license = "AGPL-3.0-or-later"
version = "0.1.0"
authors = ["phiresky <phireskyde+git@gmail.com>"]
edition = "2018"
default-run = "rga"
exclude = [
    "exampledir/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree_magic = { package = "tree_magic_fork", version="0.2" }
regex = "1.1.6"
rkv = "0.9.5"
cachedir = "0.1.1"
path-clean = "0.1.0"
bincode = "1.1.4"
serde = { version="1.0.92", features = ["derive"] }
zstd = "0.4.24"
lazy_static = "1.3.0"
serde_json = "1.0.39"
failure = "0.1.5"
